try 
{
    // console.log(program);
    console.log("Program ran successfully");    
} catch (err) 
{
    console.log("This is an error");
    // console.log(err);
}
finally
{
    console.log("This is finall code");
}
// finally will run if there error in catch also.
